name: test-workflow


# Manual trigger with parameters
on:
  workflow_dispatch
  
jobs:

  Build:
    runs-on: ubuntu-latest

    # Checkout code
    steps:
    - name: display environments 
      uses: actions/checkout@v2     
   
        
    - name: display stage variables
      run: echo '$variable1'
